### ISSUE TITLE
Raw files

### ISSUE THREAD

**Issue by N6REJ** [drcursor/flickrup#1]
Does this work with raw files like nikon .nef?

**Comment by drcursor** [comment]
Unfortunately Flickr doesn't support raw uploading.

I'm thinking about adding a nef to jpg conversion (something like [this](http://superuser.com/a/577661)) , but I'm still not sure.

In the meantime I have my camera set to RAW+JPG (different cards).

I'll keep this open as a reminder. I'm also open to other suggestions.

**Comment by N6REJ** [comment]
DNG would be best... once its in .jpg you've lost a LOT of processing 
power.. dng is actually a .tiff format...sorta..
Bear

**Comment by drcursor** [comment]
No support for DNG from flickr : https://www.flickr.com/help/forum/31558/?search=lightroom
