### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by arnauldb** [drcursor/flickrup#3]
hello,

thanks for your tuto.

I installed everything but when I run : 

sudo cp flickrup.py /usb/bin

I have this : 

pi@raspberrypi:~$ sudo cp flickrup.py /usb/bin
cp: cannot stat ‘flickrup.py’: No such file or directory

any idea ?

**Comment by drcursor** [comment]
@arnauldb there was a typo on the README file, sorry about that.
Take a look at the new version.

**Comment by arnauldb** [comment]
thanks.
